# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.4
loom_version=1.17-SNAPSHOT

# Mod Properties
version=1.2.0
maven_group=me.wolfii
archives_base_name=haveiplayedwith

# Dependencies
fabric_api_version=0.158.0+26.2
h2_mvstore_version=2.4.240
